# Introduction to NumPy arrays

In [1]:
import numpy as np

In [3]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [9]:
np.arange(5, 20, 3)

array([ 5,  8, 11, 14, 17])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((5, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [27]:
np.random.rand()

0.6515040328404436

In [28]:
np.random.rand(5)

array([0.08710263, 0.84708465, 0.37716841, 0.8398025 , 0.29465906])

In [31]:
np.random.rand(2, 4)

array([[0.7138905 , 0.53314178, 0.83688241, 0.24526403],
       [0.06760633, 0.49089801, 0.34990714, 0.25915243]])

In [33]:
np.random.randn()

0.24110009401426882

In [34]:
np.random.randn(2, 4)

array([[-0.33117654,  0.47914952,  0.68851562, -0.48837362],
       [-0.62465789, -0.88191684,  0.39493439, -0.03013795]])

In [48]:
np.random.seed(100)

In [49]:
np.random.rand((5))

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [56]:
np.random.randint(1, 100, (3,3))

array([[94, 87,  3],
       [28,  5, 32],
       [ 2, 14, 84]])

In [61]:
array = np.arange(0, 24)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
array.reshape((6, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
array.reshape((4, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [66]:
array.reshape((12, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [71]:
array = np.random.randint(1, 100, 10)
array

array([56, 72, 81,  3, 95, 20, 99, 64, 54, 28])

In [72]:
array.sum()

572

In [74]:
array.min()

3

In [75]:
array.max()

99

In [79]:
array.mean()

57.2

In [81]:
np.average(array)

57.2

In [82]:
np.cos(array)

array([ 0.85322011, -0.96725059,  0.77668598, -0.9899925 ,  0.73017356,
        0.40808206,  0.03982088,  0.39185723, -0.82930983, -0.96260587])

In [83]:
np.max(array)

99

In [85]:
array.argmax()

6

In [86]:
array.argmin()

3

In [88]:
array.shape

(10,)

In [92]:
np.zeros((2,3)).shape

(2, 3)

In [93]:
array.dtype

dtype('int32')

# NunPy array indexing and selection

In [96]:
array = np.random.randint(1, 100, 10)
array

array([35, 54, 75, 18, 73, 14, 31, 18, 54, 69])

In [97]:
array[8]

54

In [98]:
array[8] = 152
array

array([ 35,  54,  75,  18,  73,  14,  31,  18, 152,  69])

In [101]:
array[3:7]

array([50, 50, 50, 50])

In [100]:
array[3:7] = [50]
array

array([ 35,  54,  75,  50,  50,  50,  50,  18, 152,  69])

In [108]:
aux_array = array[3:7]
aux_array[1:3] = 0
print(aux_array)
print(array)

[99  0  0 99]
[ 35  54  75  99   0   0  99  18 152  69]


In [145]:
matrix = np.random.randint(1, 100, (10,10))
matrix

array([[39, 41, 54, 94, 15, 39, 87, 38,  1, 60],
       [42, 45, 20, 77, 67, 14, 88, 66, 69, 55],
       [ 1, 88, 84, 11, 66,  3, 88, 77, 40, 37],
       [36, 27, 20,  5, 40, 88, 75, 80, 93, 53],
       [45, 14, 34, 16, 18, 89, 24, 60,  9, 41],
       [78, 48, 46, 26, 32, 11, 39, 81, 88, 85],
       [61, 18, 16, 86, 20, 21,  4, 75, 60, 12],
       [49,  7, 91, 18, 77, 59, 73,  1, 52, 31],
       [83, 28, 71, 54, 40, 52, 97, 46, 40, 89],
       [51, 47, 61, 81, 70, 81, 35, 82, 87, 17]])

In [113]:
matrix[2:5, 3:6]

array([[97, 75, 54],
       [14, 82, 26],
       [88, 52, 49]])

In [143]:
matrix[2:5, 3:6] = -1

In [146]:
matrix

array([[39, 41, 54, 94, 15, 39, 87, 38,  1, 60],
       [42, 45, 20, 77, 67, 14, 88, 66, 69, 55],
       [ 1, 88, 84, 11, 66,  3, 88, 77, 40, 37],
       [36, 27, 20,  5, 40, 88, 75, 80, 93, 53],
       [45, 14, 34, 16, 18, 89, 24, 60,  9, 41],
       [78, 48, 46, 26, 32, 11, 39, 81, 88, 85],
       [61, 18, 16, 86, 20, 21,  4, 75, 60, 12],
       [49,  7, 91, 18, 77, 59, 73,  1, 52, 31],
       [83, 28, 71, 54, 40, 52, 97, 46, 40, 89],
       [51, 47, 61, 81, 70, 81, 35, 82, 87, 17]])

In [151]:
matrix = np.random.randint(1, 100, (8,8))
matrix

array([[89, 20, 28, 22,  1, 74,  2, 37],
       [52, 34, 97, 87, 27, 87, 93,  7],
       [95,  4, 29, 36, 32, 20, 53, 42],
       [79, 51, 47, 72, 50, 51, 78, 59],
       [77,  3, 62, 61, 19, 36,  3, 56],
       [97, 64, 71, 26, 96, 57, 59, 83],
       [77, 61, 18, 34, 67, 95, 19, 67],
       [37,  8, 63,  2, 86, 78, 58, 31]])

In [159]:
(matrix>=50) & (matrix<=80)

array([[False, False, False, False, False,  True, False, False],
       [ True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False],
       [ True,  True, False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False, False, False,  True],
       [False,  True,  True, False, False,  True,  True, False],
       [ True,  True, False, False,  True, False, False,  True],
       [False, False,  True, False, False,  True,  True, False]])

In [160]:
matrix[(matrix>=50) & (matrix<=80)]

array([74, 52, 53, 79, 51, 72, 50, 51, 78, 59, 77, 62, 61, 56, 64, 71, 57,
       59, 77, 61, 67, 67, 63, 78, 58])

In [162]:
matrix+5

array([[ 94,  25,  33,  27,   6,  79,   7,  42],
       [ 57,  39, 102,  92,  32,  92,  98,  12],
       [100,   9,  34,  41,  37,  25,  58,  47],
       [ 84,  56,  52,  77,  55,  56,  83,  64],
       [ 82,   8,  67,  66,  24,  41,   8,  61],
       [102,  69,  76,  31, 101,  62,  64,  88],
       [ 82,  66,  23,  39,  72, 100,  24,  72],
       [ 42,  13,  68,   7,  91,  83,  63,  36]])

In [163]:
matrix-5

array([[84, 15, 23, 17, -4, 69, -3, 32],
       [47, 29, 92, 82, 22, 82, 88,  2],
       [90, -1, 24, 31, 27, 15, 48, 37],
       [74, 46, 42, 67, 45, 46, 73, 54],
       [72, -2, 57, 56, 14, 31, -2, 51],
       [92, 59, 66, 21, 91, 52, 54, 78],
       [72, 56, 13, 29, 62, 90, 14, 62],
       [32,  3, 58, -3, 81, 73, 53, 26]])

In [164]:
matrix*5

array([[445, 100, 140, 110,   5, 370,  10, 185],
       [260, 170, 485, 435, 135, 435, 465,  35],
       [475,  20, 145, 180, 160, 100, 265, 210],
       [395, 255, 235, 360, 250, 255, 390, 295],
       [385,  15, 310, 305,  95, 180,  15, 280],
       [485, 320, 355, 130, 480, 285, 295, 415],
       [385, 305,  90, 170, 335, 475,  95, 335],
       [185,  40, 315,  10, 430, 390, 290, 155]])

In [165]:
np.abs(matrix)

array([[89, 20, 28, 22,  1, 74,  2, 37],
       [52, 34, 97, 87, 27, 87, 93,  7],
       [95,  4, 29, 36, 32, 20, 53, 42],
       [79, 51, 47, 72, 50, 51, 78, 59],
       [77,  3, 62, 61, 19, 36,  3, 56],
       [97, 64, 71, 26, 96, 57, 59, 83],
       [77, 61, 18, 34, 67, 95, 19, 67],
       [37,  8, 63,  2, 86, 78, 58, 31]])

In [166]:
matrix/100

array([[0.89, 0.2 , 0.28, 0.22, 0.01, 0.74, 0.02, 0.37],
       [0.52, 0.34, 0.97, 0.87, 0.27, 0.87, 0.93, 0.07],
       [0.95, 0.04, 0.29, 0.36, 0.32, 0.2 , 0.53, 0.42],
       [0.79, 0.51, 0.47, 0.72, 0.5 , 0.51, 0.78, 0.59],
       [0.77, 0.03, 0.62, 0.61, 0.19, 0.36, 0.03, 0.56],
       [0.97, 0.64, 0.71, 0.26, 0.96, 0.57, 0.59, 0.83],
       [0.77, 0.61, 0.18, 0.34, 0.67, 0.95, 0.19, 0.67],
       [0.37, 0.08, 0.63, 0.02, 0.86, 0.78, 0.58, 0.31]])

In [168]:
50/matrix

array([[ 0.56179775,  2.5       ,  1.78571429,  2.27272727, 50.        ,
         0.67567568, 25.        ,  1.35135135],
       [ 0.96153846,  1.47058824,  0.51546392,  0.57471264,  1.85185185,
         0.57471264,  0.53763441,  7.14285714],
       [ 0.52631579, 12.5       ,  1.72413793,  1.38888889,  1.5625    ,
         2.5       ,  0.94339623,  1.19047619],
       [ 0.63291139,  0.98039216,  1.06382979,  0.69444444,  1.        ,
         0.98039216,  0.64102564,  0.84745763],
       [ 0.64935065, 16.66666667,  0.80645161,  0.81967213,  2.63157895,
         1.38888889, 16.66666667,  0.89285714],
       [ 0.51546392,  0.78125   ,  0.70422535,  1.92307692,  0.52083333,
         0.87719298,  0.84745763,  0.60240964],
       [ 0.64935065,  0.81967213,  2.77777778,  1.47058824,  0.74626866,
         0.52631579,  2.63157895,  0.74626866],
       [ 1.35135135,  6.25      ,  0.79365079, 25.        ,  0.58139535,
         0.64102564,  0.86206897,  1.61290323]])